language: "python"
python:
  - "3.6"
services:
  - postgresql
env:
  - DJANGO=2.0
install:
  - pip install -r requirements.txt
before_script:
  - python manage.py makemigrations hacker
  - python manage.py migrate --run-syncdb
script:
  - python manage.py test
