# https://cloud.google.com/kubernetes-engine/docs/tutorials/gitops-cloud-build
steps:
# This step runs the Django unit tests
- name: 'python:3.7-slim'
  id: Test
  entrypoint: /bin/sh
  args:
  - -c
  - 'pip install -r requirements.txt && cd ouroboros && python manage.py test'