version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/SECRET_POSTGRES_PASS
      POSTGRES_USER_FILE: /run/secrets/SECRET_POSTGRES_USER
      POSTGRES_DB: ouroboros
    secrets:
      - SECRET_POSTGRES_PASS
      - SECRET_POSTGRES_USER

  app:
    command: python manage.py runserver --settings=ouroboros.settings.prod 0.0.0.0:8000
    secrets:
      - SECRET_POSTGRES_PASS
      - SECRET_POSTGRES_USER
      - SECRET_EMAIL_CONFIG
      - SECRET_DJANGO_KEY

secrets:
  SECRET_DJANGO_KEY:
    file: ouroboros/config/SECRET_DJANGO_KEY
  SECRET_POSTGRES_PASS:
    file: ouroboros/config/SECRET_POSTGRES_PASS
  SECRET_POSTGRES_USER:
    file: ouroboros/config/SECRET_POSTGRES_USER
  SECRET_EMAIL_CONFIG:
    file: ouroboros/config/SECRET_EMAIL_CONFIG.json

volumes:
  resume_storage: