# Generated by Django 2.2.10 on 2021-08-01 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20200630_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='additional_accommodations',
            field=models.TextField(blank=True, max_length=500, verbose_name='Do you require any special accommodations at the event?'),
        ),
        migrations.AddField(
            model_name='application',
            name='agree_to_td_policies',
            field=models.BooleanField(choices=[(True, 'Agree')], default=None, help_text="I agree to TAMU Datathon's Talent Release and Liability terms."),
        ),
        migrations.AddField(
            model_name='application',
            name='dietary_restrictions',
            field=models.CharField(choices=[('None', None), ('Vegan', 'Vegan'), ('Vegetarian', 'Vegetarian'), ('Halal', 'Halal'), ('Kosher', 'Kosher'), ('Gluten-free', 'Gluten-free'), ('Food allergy', 'Food allergy'), ('Other', 'Other')], default='None', max_length=50, verbose_name='Do you have any dietary restrictions?'),
        ),
        migrations.AddField(
            model_name='application',
            name='shirt_size',
            field=models.CharField(choices=[('XXS', 'Unisex XXS'), ('XS', 'Unisex XS'), ('S', 'Unisex S'), ('M', 'Unisex M'), ('L', 'Unisex L'), ('XL', 'Unisex XL'), ('XXL', 'Unisex XXL')], default='M', max_length=4, verbose_name='What size shirt do you wear?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='transport_needed',
            field=models.CharField(choices=[('D', 'Driving'), ('OB', 'Bus (Greyhound, Megabus, etc.)'), ('F', 'Flying'), ('P', 'Public Transportation'), ('M', 'Walking/Biking')], default='M', max_length=11, verbose_name='How will you be getting to the event?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='travel_reimbursement',
            field=models.BooleanField(default=False, help_text='Travel reimbursement is only provided if you stay the whole time and submit a project.', verbose_name="I'd like to apply for travel reimbursement"),
        ),
        migrations.AlterField(
            model_name='application',
            name='grad_year',
            field=models.IntegerField(choices=[(2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], verbose_name='What is your anticipated graduation year?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='is_adult',
            field=models.BooleanField(choices=[(True, 'Agree')], default=None, help_text='Please note that freshmen under 18 must be accompanied by an adult or prove that they go to Texas A&M University.', verbose_name='Please confirm you are 18 or older.'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('P', 'Under Review'), ('R', 'Waitlisted'), ('V', 'Admitted for Virtual'), ('A', 'Admitted for In Person'), ('C', 'Confirmed'), ('X', 'Declined'), ('I', 'Checked in'), ('E', 'Expired')], default='P', max_length=1),
        ),
    ]
