# Generated by Django 2.2.10 on 2021-08-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20210731_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='agree_to_td_policies',
            field=models.BooleanField(choices=[(True, 'Agree')], default=None),
        ),
        migrations.AlterField(
            model_name='application',
            name='is_adult',
            field=models.BooleanField(choices=[(True, 'Agree')], default=None, help_text='Please note that freshmen under 18 must be accompanied by an adult or prove that they go to Texas A&M University. Contact us at connect@tamudatathon.com for questions', verbose_name='I am 18 years old or older.'),
        ),
    ]
