# Generated by Django 2.2.10 on 2021-08-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20210731_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='location_preference',
            field=models.CharField(choices=[('prefers_in_person', 'Prefer participating in person'), ('prefers_virtual', 'Prefer participating virtually')], default='prefers_in_person', max_length=24, verbose_name='Location Preference'),
        ),
        migrations.AlterField(
            model_name='application',
            name='is_adult',
            field=models.BooleanField(choices=[(True, 'Agree')], default=None, help_text='Please note that freshmen under 18 must be accompanied by an adult or prove that they go to Texas A&M University. Contact us at connect@tamudatathon.com if you have any questions.', verbose_name='I am 18 years old or older.'),
        ),
        migrations.AlterField(
            model_name='application',
            name='transport_needed',
            field=models.CharField(blank=True, choices=[('D', 'Driving'), ('OB', 'Bus (Greyhound, Megabus, etc.)'), ('F', 'Flying'), ('P', 'Public Transportation'), ('M', 'Walking/Biking')], max_length=50, verbose_name='How will you be getting to the event?'),
        ),
    ]
