# Generated by Django 2.2.10 on 2021-08-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20210801_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='attending_with',
            field=models.TextField(blank=True, help_text='Keep in mind they will also need to apply and fill out this form.', max_length=1000, verbose_name='If your planning on attending with other people, please list their full names here.'),
        ),
    ]
