# Generated by Django 2.2.10 on 2022-08-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_auto_20210803_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='grad_year',
            field=models.IntegerField(choices=[(2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026)], verbose_name='What is your anticipated graduation year?'),
        ),
    ]
