# Generated by Django 2.2.10 on 2022-08-28 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_auto_20220827_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='travel_reimbursement',
        ),
    ]
